export const SET_TIMER_STYLE = 'SET_TIMER_STYLE';
export const SET_START = 'SET_START';
export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASK_STATUS = 'UPDATE_TASK_STATUS';
export const UPDATE_SESSIONS = 'UPDATE_SESSIONS';
export const RESET_TIMER_STATISTICS = 'RESET_TIMER_STATISTICS';
